### ISSUE TITLE
Data not readable without Data export rights

### ISSUE THREAD

**Issue by ThomasVermes** [lsgs/redcap-extended-reports#17]
Dear Luke,
i'm posting here a copy of my post in the redcap community you might have overseen.
Though, I've read you were away for some time and you might not be able to reach everyone out
Furthermore, I'm not sure is a bug or an expected behaviour

https://redcap.vanderbilt.edu/community/post.php?id=210241&comment=222277

in order to see data from an instrument a user needs to have set the Data Export Rights for that instrument at least to the "De-Identified*"
 
![image](https://github.com/lsgs/redcap-extended-reports/assets/75424115/276a5eeb-247f-4f3b-950b-39d87e3f6093)

With "No Access" on the "Data Export rights", but "Data Viewing Rights" set on "view & edit" the field will be empty(s)
 
![image](https://github.com/lsgs/redcap-extended-reports/assets/75424115/a17bd391-57dc-4ec1-8345-199cf3088871)

This issue cannot be verified using the
![image](https://github.com/lsgs/redcap-extended-reports/assets/75424115/0d39a240-73ba-4233-a0c5-b645c9dbd432)
Since data are then show.

I discover this issue through a normal user.

I think this a something to do with the [@leila.deering](https://redcap.vanderbilt.edu/community/profile.php?id=125) issue (this post here above, date :2023-08-21 16:48)

 

The module doens't seem to check the Data Viewing Rights, is that an expected behaviour?

best

Thomas

**Comment by lsgs** [comment]
Thanks for the report @ThomasVermes. I've found out that this is happening because the `REDCap::getReport` plugin method assumes the purpose is for export, and therefore does not consider form visibility permissions in returning its output, only export permissions. The consequence of this was what you see above - fields on forms with permissions for view are shown empty, because they're not present in the data returned by the method.
I've been working on a fix for this and a couple of other things. I want to get a new release done asap...

**Comment by ThomasVermes** [comment]
It seems to work with the last release! Thank you very much!!
