### ISSUE TITLE
Enhancement: Allow Extended Reports uing SQL to feed Smart Variables

### ISSUE THREAD

**Issue by aboulang** [lsgs/redcap-extended-reports#36]
A smart variable like [aggregate-count:participant_id:R-611TRM7LJN]  returns a count of 0 when the report, R-611TRM7LJN] is an Extended Report and its SQL returns a result set with a participant_Id column.

**Comment by lsgs** [comment]
Yes, @aboulang. This is, unfortunately, expected behavior - a limitation. When a report is run for the purposes of a smart-variable parameter, there is no opportunity for the module to intercept it to inject the custom processing. I've added a note to the readme that will get into the next release. Thanks

**Comment by lsgs** [comment]
The new note will appear in v2.3.2, just released
